algoritmo "CONTADOR"

var
    incremento , f , i: real
inicio
      escreva("Digite o ultimo valor")
      leia(f)
      escreva("Digite o primeiro valor")
      leia(i)
      escreva("Digite o passe ")
      leia(incremento)
      enquanto (f >= i) faça  //enquanto f FOR maior ou igual a I
      escreval (I)
               I <- I + incremento
      FimEnquanto
      escreva("Acabou")


fimalgoritmo